### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by edelooff** [jennschiffer/timbles.js#19]
The code style of the plugin and the associated tests do not form a nice and consistent story. Even the code within the plugin is a bit of a mix.

Is there a code style that applies to Timbles, or is that still a choice to be made? I had a brief look at the [jQuery Style Guide](https://contribute.jquery.org/style-guide/js/) which seems like it would be a reasonable choice given the heritage. Personally I think it's a bit heavy on internal whitespace (args, params), but otherwise seems alright as a starting point.

Having a short pointer to a style guide and possible small deviations from it ought to help keep things nice and consistent.

**Comment by edelooff** [comment]
As a suggestion:

Timbles follows jQuery style with the following exceptions (based on the rules implied by existing code)
- Indentation is in spaces, with 2 spaces per indentation level
- Prefer single quotes (`'`) over double quotes (`"`)

**Comment by jennschiffer** [comment]
yeah the code style was originally what i was using at the nba when i first started working with a similar plugin. originally there were tabs but my editor had at some point replaced that all lol, why do i even computer

**Comment by jennschiffer** [comment]
it makes sense to use the jquery style so after you merge the other PR I can go ahead and jquery style-ify it all.

**Comment by edelooff** [comment]
I was going to say something along the lines of really preferring spaces to tabs and editor woes, but then I remembered [editorconfig](http://editorconfig.org/). Something like the following should help with keeping our style consistent without too much effort (and fits unaltered jQuery style).

```
[*]
indent_style = tab
tab_width = 4

end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

I still do prefer single quotes over doubles as they're half the keystrokes, but that's hardly an issue worth fighting over.

**Comment by jennschiffer** [comment]
i prefer single and 2 spaces myself tbqh

**Comment by jennschiffer** [comment]
single quotes that is

**Comment by edelooff** [comment]
Awesome, I'm quite happy with that as well.

I just opened a new branch (833c5119c2b9ef964908471e9314edddb6d9e70e) for code style fixes and added an editorconfig to that. We should probably document the code style in a `CONTRIBUTING` file or something like that.
